### ISSUE TITLE
SessionStorage for Account creation process

### ISSUE THREAD

**Issue by hskang9** [GetSpeckle/speckle-browser-extension#65]
# Problem
Opening a popup in chrome extension means it is reloading the web app, and it will not save the last state upon account creation. 

# What I can do
Apply sessionStorage
[source](https://stackoverflow.com/questions/9089793/chrome-extension-simple-popup-wont-remain-in-last-state)

# Cute animal picture

![image](https://user-images.githubusercontent.com/12888144/57570950-89cba900-7442-11e9-9604-d8fc751304a6.png)

**Comment by anjj123** [comment]
@fyang1024 @ttaoS @mytechtip do we need this?

**Comment by fyang1024** [comment]
Thank @hskang9 for raising the issue. Yes, currently we don't persist every state in either session storage or local storage now, which means when the extension popup close, some state is lost, so that user sees a different screen when they open the extension again. 
We do persist the following states in local storage:
* whether or not it's the first time the user uses the extension.
* color
* selected network
* selected account
* accounts
These states may not be enough to make sure user will see the same screen after re-open the extension.

I think we need to identify which screen and its data that needs to survive the close and re-opening.
We may not want this scenario happen:
User tries to create a new wallet and she types and confirms the password
She sees seed phrase screen
She close the extension
She re-open the extension, do we want her to continue without re-typing/confirming password? probably not.

Let's identify which screen and its data that needs to survive the close and re-opening first

**Comment by anjj123** [comment]
One example (and a topic commonly received from feedback) is storing the mnemonic in a pwd manager or some other offscreen software. When closed, the extension restarts the process and so it's practically impossible to store the seed in any way other than writing it down. 

Could we persist the mnemonic and/or the user's current step in creating a wallet in sessionStorage for an allotted period of time and display that timer?

**Comment by anjj123** [comment]
@hskang9 @fyang1024 is this still a live issue? we have the account creation flow being worked on atm or are we considering persisting other states in storage?

**Comment by fyang1024** [comment]
I believe it can be closed. Correct me if I am wrong @hskang9

**Comment by hskang9** [comment]
Yes it can be closed for this. Mnemonic is persisted after closing. Timer is left for now for design and implementation and I think it should be on a separate issue.
